config/routes.rb
Rails.application.routes.draw do
  root 'movies#index'

  get 'movies/index'

  post 'movies/save_movie'

  get 'movies/show'

end

app/models/movie.rb
class Movie < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
  end

  def save_movie
    if params[:title].present? && params[:studio].present? && params[:genre].present?
    Movie.new(
              title: params[:title],
              genre: params[:genre],
              year: params[:year],
              rating: params[:rating],
              studio: params[:studio]
      ).save

      redirect_to movies_index_path, notice:"Pelicula Creada"
    else
      flash[:alert] = "Complete todos los datos"
      render :index
    end
  end

  def show
    @movies = Movie.all.reverse
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MovieDB</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
<%= yield %>
</div>

</body>
</html>

app/views/movies/index.html.erb
<div class = "jumbotron">
	<h1>Ingreso de Películas</h1>
	<% if notice %>
	<div class="alert alert-success" role="alert">
	<strong>Excelente!</strong> <%= notice %>
	</div>
	<% elsif alert %>
	<div class="alert alert-warning" role="alert">
	<strong>Warning!</strong> <%= alert %>
	</div>
	<% end %>

<%= form_tag movies_save_movie_path, method: "post" do %>
	<div class="form-group">
		<%= label_tag :title, 'Título Película' %>
		<%= text_field_tag :title, params[:title] , class: "form-control" %>
	</div>
	<div class="form-group">
		<%= label_tag :genre, 'Género' %>
		<%= text_field_tag :genre, params[:genre] , class: "form-control" %>
	</div>
	<div class="form-group">
		<%= label_tag :year, 'Año' %>
		<%= text_field_tag :year, params[:year] , class: "form-control" %>
	</div>
	<div class="form-group">
		<%= label_tag :rating, 'Rating' %>
		<%= text_field_tag :rating, params[:rating] , class: "form-control" %>
	</div>
	<div class="form-group">
		<%= label_tag :studio, 'Estudio' %>
		<%= text_field_tag :studio, params[:studio] , class: "form-control" %>
	</div>
	<div class="form-group">
		<%= submit_tag "Enviar", class:"btn btn-success" %>
		<a href="/movies/show" class="btn btn-success" role="button">Mostrar películas</a>
	</div>
<% end %>

</div>

app/views/movies/show.html.erb
<div class="jumbotron">
<h1>Lista de películas</h1>
<table class="table table-striped table-bordered">
	<thead>
		<tr>
			<th>Título</th>
			<th>Género</th>
			<th>Año</th>
			<th>Rating</th>
			<th>Estudio</th>
		</tr>
	</thead>
	<tbody>
		
		<% @movies.each do |movie| %>
		<tr>
			<td><%= movie.title %></td>	
			<td><%= movie.genre %></td>	
			<td><%= movie.year %></td>	
			<td><%= movie.rating %></td>	
			<td><%= movie.studio %></td>	
			</tr>
		<% end %>	
		
	</tbody>
</table>

<div>
<a href="/" class="btn btn-primary btn-lg active" role="button">Agregar otra película</a>
</div>